//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoTarjetasDeCredito
    {
        public int NumeroTarjeta { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int EstadoTarjeta { get; set; }
    
        public virtual TarjetaDeCredito TarjetaDeCredito { get; set; }
    }
}
