//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaDeCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarjetaDeCredito()
        {
            this.HistoricoTarjetasDeCredito = new HashSet<HistoricoTarjetasDeCredito>();
            this.TarjetaDeCredito1 = new HashSet<TarjetaDeCredito>();
        }
    
        public int NumeroTarjeta { get; set; }
        public int Marca { get; set; }
        public int SaldoMaximo { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Extension { get; set; }
        public int DNICliente { get; set; }
        public int Estado { get; set; }
    
        public virtual ClienteTitular ClienteTitular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoTarjetasDeCredito> HistoricoTarjetasDeCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetaDeCredito> TarjetaDeCredito1 { get; set; }
        public virtual TarjetaDeCredito TarjetaDeCredito2 { get; set; }
    }
}
